### ISSUE TITLE
Device.Type Issues

### ISSUE THREAD

**Issue by IvanProdaiko94** [faisalman/ua-parser-js#224]
Hello!
It seems that in version: '0.7.12' device type detection is broken.
I mean that:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.13 Safari/537.36 { ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.13 Safari/537.36'`

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.19 Safari/537.36`
in both UA library returned totally undefined device type, vendor and name.

**Comment by nosovk** [comment]
Just checked - confirm, looks like device type detection is broken.

**Comment by vovax87** [comment]
I had the same bug as well - hope someone can help

**Comment by sheinbergon** [comment]
This is not a bug. Device types for desktops will always be "undefined" because unlink other devices, they're not explicitly included inside the UserAgent ( Mac is sort of an exception , and it's more of a desktop type variation then an actual device type ) 

See this discussion for more details - https://github.com/faisalman/ua-parser-js/issues/182
