### ISSUE TITLE
Facebook web view 

### ISSUE THREAD

**Issue by fverdicchio** [faisalman/ua-parser-js#225]
Facebook web view return browser name chrome for android and Facebook for ios. Could be util, for web view, add a field for app source(name and version)

**Comment by ebbmo** [comment]
Hi,

I have the same (a similar) issue. The Facebook InApp Browser (which accounts for a HUGE part of traffic nowadays) should (IMO) be identified accordingly, but is currently **not identified** for the **Android Facebook App**.

If I have a UA as follows: 
`Mozilla/5.0 (Linux; Android 6.0.1; ONE A2003 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/123.0.0.18.71;]` the result would be
**BrowserName:** Chrome WebView
**BrowserVersion:** 58.0.3029.83

While this is true (The InApp browser being no more than a webview of the currently installed browser) the UA actually holds **more** information: The existence of FB_IAB means it was the FB In App Browser (for ANDROID). 

When using the IOS App (with a UA: `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304 [FBAN/FBIOS;FBAV/91.0.0.41.73;FBBV/57050710;FBDV/iPhone8,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3.1;FBSS/2;FBCR/Telekom.de;FBID/phone;FBLC/de_DE;FBOP/5;FBRV/0])` the result actually differs:
**BrowserName:** Facebook
**BrowserVersion:** 91.0.0.41.73
as well as the additional information for the Engine
**EngineName:** WebKit
**EngineVersion:** 603.1.30

I understand that the Android UA does not hold as much information as the IOS UA, but could we at least:
- exchange the BrowserName with Facebook
- drop the Version?

Since i'm not too sure whether WebView can actually be called an 'engine' I would leave the judgement to you of whether or not to include it...

Let me know what you think and I could open a PR.

KR,
ebbmo

**Comment by faisalman** [comment]
@ebbmo agree, should be detected as FB as well in Android, please do a PR if you want to :+1:

**Comment by ebbmo** [comment]
@faisalman [PR is up](https://github.com/faisalman/ua-parser-js/pull/242). Let me know if anything is missing.
