### ISSUE TITLE
IE 11 is not detected on server side (node)

### ISSUE THREAD

**Issue by bwidtmann** [faisalman/ua-parser-js#226]
IE 11 is using different user agents on client side (navigator.userAgent) and server side (request header user-agent) -> see http://stackoverflow.com/questions/24999266/internet-explorer-user-agent-header-differs-in-http-call-versus-navigator-userag

navigator.userAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; rv:11.0) like Gecko

request header user-agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; WOW64; Trident/7.0)

while using ua-parser with the first user agent, IE 11 is detected correctly. But using ua-parser with second user agent IE 11 is detected as IE 10

so client app and server app are making different decisions.

**Comment by ebbmo** [comment]
Hi @bwidtmann,

Interesting point, but that is actually nothing this library can solve, is it? 
When the User Agent changes then each one of them will be interpreted independently.

And taking the 2nd User Agent you can read: **MSIE 10.0**, which means the ua-parser can only deduct this UA to be IE10...

Therefore I think this issue should be closed, because this is a technical issue with how IE works and not this library.

KR, ebbmo

**Comment by faisalman** [comment]
Thanks @bwidtmann for reporting this issue but @ebbmo has a good point, the problem described isn't within the domain this library can or try to solve..
