### ISSUE TITLE
getResult() changed definition and is no longer returning JSON - but no major version change in the module

### ISSUE THREAD

**Issue by freeall** [faisalman/ua-parser-js#258]
I was having an issue in production where `ua-parser-js` would cause errors. I could not figure out what it was, but it turns out that it was because that from `0.7.12` to `0.7.14` it changed api.

Normally `getResult()` would return a JSON object. Now it returns an Object with the `Browser`, `UA`, `Device` objects in it. Which makes it unusable in some cases. In my case we wrapped it with ImmutableJS, which didn't seem to work.

Since the API changed I think it should have been a major version change, because this can cause problem in live systems. In my case, it did.

Btw, is there a reason this module doesn't only expose one method, that returns one JSON object, instead of having the `getBrowser`, `getOS`, etc, methods?

**Comment by faisalman** [comment]
Hi @freeall sorry I didn't aware of it, should've create a unit test for the result, maybe I'll revert it and mark as 0.7.15

The reason behind exposing many methods is, for example, when you only need browser information, rather than using `getResult()` which will process all regexes, `getBrowser()` will give you extra performance by only processing relevant regexes..

**Comment by freeall** [comment]
Regexes are pretty fast and works in linear on the input, so it wouldn't be too slow unless you are doing millions of checks.

**Comment by faisalman** [comment]
Merged
