### ISSUE TITLE
Regular expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by donaldhansen** [faisalman/ua-parser-js#342]
Recently had code ran through NexusIQ and it flagged the _ua-parser-js_ library as vulnerable to ReDoS. We have been told we need to find a new solution by end of year. 

Does anyone have suggestions on how to safeguard this library against ReDoS?

**Comment by sumitkm** [comment]
I am no JS security expert so please take my suggestions 'lightly'. Here is what I read up about ReDoS [on the OWASP](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) site.

From what I understand ua-parser.js has set of reg-exes that can be pwned by a carefully crafted string. However, since the only string the ua-parser.js needs is the navigator's UA string, one could argue ua-parser shouldn't take that value as an optional input string and always query the navigator itself. That way it can't take any inputs that can send it off to a tizzy. (I understand this is probably a breaking change so security concious people should try it out with their own fork first).

That plan however breaks down when evil guy crafts a naughty UA string and send it your way, specially if you are running this on server. Not sure...

Wondering how to test this hypothesis... 🤔

**Comment by abdulhannanali** [comment]
If you are looking for a ua-parser with safe regular expressions https://github.com/3rd-Eden/useragent is a lot better option. It relies on https://github.com/ua-parser/uap-core which tests it's regular expressions for redos vulnerabilities and regular expressions are crafted keeping in view the redos.

**Comment by thepassle** [comment]
Is this something that will be fixed? Browser-sync depends on this package, and it's currently blocking for us

**Comment by m-mercuri** [comment]
Hi! I'm still getting the vulnerability error from [sonatype](https://ossindex.sonatype.org/vulnerability/sonatype-2018-0272?component-type=npm&component-name=ua-parser-js) for the latest version (`1.0.2`):
```
[5/5] - pkg:npm/ua-parser-js@1.0.2 - 1 vulnerability found!

  Vulnerability Title:  [sonatype-2018-0272] CWE-185: Incorrect Regular Expression
  ID:  sonatype-2018-0272
  Description:  ua-parser-js - Regular Expression Denial of Service (ReDoS)

  The software specifies a regular expression in a way that causes data to be improperly matched or compared.
  CVSS Score:  5.9
  CVSS Vector:  CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
  Reference:  https://ossindex.sonatype.org/vulnerability/sonatype-2018-0272?component-type=npm&component-name=ua-parser-js&utm_source=auditjs&utm_medium=integration&utm_content=4.0.36
```

Is there a plan to fix this soon?

Thanks for all the work! :)
