### ISSUE TITLE
Optimize getResult() by sorting regexes by popularity

### ISSUE THREAD

**Issue by AaronO** [faisalman/ua-parser-js#401]
We use Amplitude, who use their own [forked version](https://github.com/amplitude/ua-parser-js) of this library in [their browser SDK](https://github.com/amplitude/Amplitude-JavaScript/).

A big chunk of Amplitude's initialization time is spent in `ua-parser`'s `getResult()`, see profile below:

![image](https://user-images.githubusercontent.com/949223/69623392-1a668100-1043-11ea-95a3-3ce1c4e534db.png)

This profile is for Chrome running on macOS on a MacBook Pro.

Given that our detection logic is basically, scan through the `userAgent` string with a list of regexes until one matches then stop. The worst case is O(n) where `n` is the number of regexes (per feature we're detecting, browser/os/device/etc ...)

We can't optimize the worst case scenario without radically changing this library's design (e.g: to a one-pass parse of the userAgent), but we can significantly improve the performance of the common case for popular configurations.

If we focus on the list of `os` regexes, `macOS` & `iOS` are near the end, whereas less popular OSes (e.g: blackberry, nintendo/playstation, ...), which means the `rgx()` call with have to test all those lesser popular platforms before getting to iOS/macOS.

The same is true for the `browser` regexes, Chrome is near the end of that list despite being the most popular browser on the market.

Additionally there doesn't seem to be an overlap between regexes that would require running some of them before others for correctness. So it seems like a no-brainer to sort regexes by their popularity (Chrome, Edge, Firefox, Safari, ...), (Windows, Android, iOS, Mac, ...)

**Comment by faisalman** [comment]
Hi @AaronO thanks for opening this issue :+1: I'll consider to revamp the structure of library to achieve better performance in future releases.

While I agree that ordering by popularity will drastically improve performance in `getDevice()` or `getOS()`, but for `getBrowser()` I think there will be an issue. Take these user agents for example:

```
# Opera
Mozilla / 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 79.0.3945.79 Safari / 537.36 OPR / 65.0.3467.72

# Edge
Mozilla / 5.0 (Windows NT 10.0; WOW64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 39.0.2171.71 Safari / 537.36 Edge / 12.0
```

If we sort the detection logic by popularity, these browsers will be captured as Chrome instead of Opera or Edge. Given the historical mess of user agent string where every new browser pretends to be another browser and almost no standard naming conventions, we'll need to balance the trade between getting the best performance while still maintaining accuracy.
