### ISSUE TITLE
IE11 is not recognized, again

### ISSUE THREAD

**Issue by gyto23** [faisalman/ua-parser-js#455]
I have tested several times `ua-parser-js` to be sure that it can detect the IE11, but looks like it cannot anymore. On the other hand, support for IE11 is going to be gone by Nov 30th (as developer I am really happy about it), but some folks might need to have this support until next year to slowly transition to Edge. Anyways, I was testing it on the demo website and looks like IE doesn't not recognized, in addition `react-device-detect` is depended on this library.

![image](https://user-images.githubusercontent.com/54277098/98965501-c06aff80-24cf-11eb-9170-4307d2b20e5d.png)

**Comment by tkrotoff** [comment]
This is not because of the library itself. It's because of http://faisalman.github.io/ua-parser-js/ source code:

![Screen Shot 2020-11-16 at 19 14 50](https://user-images.githubusercontent.com/643434/99291403-0d3c3680-2840-11eb-9725-d8e2f53fb8bc.png)

![Screen Shot 2020-11-16 at 19 15 48](https://user-images.githubusercontent.com/643434/99291478-2cd35f00-2840-11eb-8c27-d42c1e783378.png)

Culprit code: https://github.com/faisalman/ua-parser-js/blob/gh-pages/index.html#L328

**Comment by gyto23** [comment]
@tkrotoff omg, you are right (I did not even think to check the console), arrow function is not supported in ie11. This is really big thing for people who trying to support ie11, should I create a PR for it?

**Comment by tkrotoff** [comment]
I'm not the maintainer :-) I guess so. You have to target gh-pages branch

**Comment by gyto23** [comment]
@tkrotoff why not master?

**Comment by faisalman** [comment]
Fixed in #457
