### ISSUE TITLE
Chrome 93.0 says that CHANGE WILL COME

### ISSUE THREAD

**Issue by The-Linguist** [faisalman/ua-parser-js#531]
### Here is what the Chrome console recently started saying,
![console](https://user-images.githubusercontent.com/50925914/135537236-31d143e9-a640-4339-938b-82d75b2be71e.jpg)

#### Now the question is, 

> ## Should we be alarmed? **Will our good apps still work then?**

**Comment by karfau** [comment]
I guess since it will take quite some time until all up to date browsers have implemented it, and ua-parser-js is also used to detect outdated browsers, it will still be helpful for quite some time.

Could it make sense to rely on the new client hint APIs when they are available and fall back to the existing UA parsing? so the API for devs doesn't change?

**Comment by faisalman** [comment]
Moving user agent client hints-related issue here: #408
