### ISSUE TITLE
IE11 on Windows7 is not recognized

### ISSUE THREAD

**Issue by kyungilpark** [faisalman/ua-parser-js#561]
Some PCs fail to detect IE11.
### Environment information
- navigator.userAgent
```js
Mozilla/5.0 (Windows NT 6.1; WOW64; APCPMS=^N201205020840572565478A37A6F9C41BD33F_9975^; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; MARKANYEPS#25118; Zoom 3.6.0; rv:11.0) like Gecko
```
- OS: Windows7 Enterprise K (SP1)
- Browser: Internet Explorer 11.0.9600.19100

<img width="543" alt="win7_ent" src="https://user-images.githubusercontent.com/483765/147762247-70824132-35f8-4eb3-8917-51dfdc7f9a39.png">
<img width="370" alt="win7_ent_ie11" src="https://user-images.githubusercontent.com/483765/147762255-74b2d816-f4cb-45b2-b34c-887156415a75.png">

### Cause
In the example, user-agent length is 271.
ua string is truncated by the following logic, so that fail to detect.
https://github.com/faisalman/ua-parser-js/blob/7ddb2575bd1c021a3e5c708ece6f6205103843d3/src/ua-parser.js#L40
https://github.com/faisalman/ua-parser-js/blob/7ddb2575bd1c021a3e5c708ece6f6205103843d3/src/ua-parser.js#L819

### So...
1. I wonder why the max limit on user-agent length has been added since v0.7.26 and why UA_MAX_LENGTH was decided to be 255.
2. It would be nice to remove the limit, but if not, I'd suggest raising it to a reasonably larger value or making it optional.

**Comment by faisalman** [comment]
From security perspective, since this library heavily relies on regular expression, historically it has been widely used as an attack vector using ReDOS vulnerability [1], thus limiting the input size of user-agent header can be used as a first line of defense [2]. 

As for the maximum length value, 255 is an arbitrary number that was chosen without particular reason other than it's a familiar number and a genuine user-agent (at least in this library's current test suite) rarely has longer. It can surely be set to a higher value if there was found to be a genuine user-agent with more length than 255.

--

[1] ua-parser-js vulnerabilities database by Snyk https://snyk.io/vuln/npm:ua-parser-js
[2] Cristian-Alexandru Staicu and Michael Pradel, _Freezing the Web: A Study of ReDoS Vulnerabilities in JavaScript-based Web Servers_, TU Darmstadt, 2017. https://www.usenix.org/conference/usenixsecurity18/presentation/staicu
