### ISSUE TITLE
use the new navigator.userAgentData with fallback to navigator.userAgent

### ISSUE THREAD

**Issue by Erdragh** [faisalman/ua-parser-js#588]
## Chromium and userAgent
As it seems, [Chromium and by extension Chrome, Edge, Brave, Opera, etc. will deprecate userAgent in the near future](https://developer.chrome.com/blog/deps-rems-100/). 

## Replacement / new Solution
The new replacement for this will be `navigator.userAgentData`.

[Here are the docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData) on userAgentData, which is still experimental and not supported by Firefox. As such userAgent should still be used as a fallback, as described here:

https://web.dev/migrate-to-ua-ch/

**Comment by tapananand** [comment]
It seems Chrome has started rolling out changes for this, are there any plans to make these changes in the near future?

**Comment by tapananand** [comment]
@faisalman Can you please comment on whether this is being considered or not?

**Comment by faisalman** [comment]
Partially yes, for browsers that are Chrome-based, I'm considering to also use `navigator.userAgentData` as a fallback whenever some particular values like `device.type` or `os.name` were not found by just simply parsing the legacy `navigator.userAgent` ..

**Comment by tapananand** [comment]
@faisalman Thanks for your response! Shouldn't the first try should be to use navigator.userAgentData since that's more structured?

**Comment by nberg79** [comment]
@faisalman 

The changes that will be enacted cause the default user agent string to have some values frozen and some values reduced. 

Currently [minor version reduction](https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-4) has rolled out (April, 2022) and the [Desktop UA reduction](https://developer.chrome.com/blog/user-agent-reduction-oct-2022-updates/) is rolling out in a phased approach from October 25th until Feb 7th. Additional information about the current phase can be found [here](https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-5). Following the Desktop UA Reduction we will start rolling out the [Mobile UA reduction](https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-6) phase on Feb 7th. 

  

These changes are being enacted to enhance privacy for end users and to help reduce digital fingerprinting. For use cases that still need the data we have developed [User-Agent Client Hints](https://web.dev/user-agent-client-hints/) as a new expansion to the Client Hints API enabling developers to access information about a user's browser in a privacy-preserving and ergonomic way. The spirit of the API is that users who need the data take action to ask for it instead of all data being provided passively.

  

There are two main ways of getting the full user agent values supported by UACH. You can specify your needs via headers or you can use the JS API to query the information you need.


I invite everyone to review the attached centralized information pertaining to the changes. Additionally I would recommend focusing on the [JS API](https://web.dev/migrate-to-ua-ch/#strategy-on-demand-client-side-javascript-api) section and checking out the [JS API demo](https://web.dev/user-agent-client-hints/#demo).

# UA-R / UA-CH Quick Start

Education
---------

* 	What are [User Agent Client Hints](https://web.dev/user-agent-client-hints/)?
* 	What happens to the [User Agent string](https://web.dev/user-agent-client-hints/#what-happens-to-the-user-agent-string)?
* 	Public GitHub: [UA-CH Explainer](https://github.com/WICG/ua-client-hints)
* 	Public feedback: [Open issues](https://github.com/WICG/ua-client-hints/issues)
    

Timeline
--------

* 	Full [UA-Reduction proposed rollout plan](https://www.chromium.org/updates/ua-reduction/)    
* 	Key Dates (As of Jan 6th, 2023) ([schedule](https://chromiumdash.appspot.com/schedule))
	* 	Chrome 100 release (Mar 29th, 2022)(Deployed)
    	* 	[User Agent Reduction Deprecation Trial](https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/) launches for instances where a site may need more migration time.
	* 	Chrome 101 release (Apr 26th, 2022)(Deployed)
		* 	Minor build version is frozen to 0.0.0 and applies to all page loads on desktop or mobile that are not part of the Reverse Origin Trial.
	* 	Chrome 107 release (Oct 25th, 2022)(Deploying)
		* 	Desktop based UA string is fully reduced for all page loads that are not part of the Reverse Origin Trial.
	* 	Chrome 110 release (Feb 7th, 2023)
    	* 	Android Mobile and Tablet based UA string is fully reduced for all page loads that are not part of the Reverse Origin Trial.
    

Migration
---------

* 	[Migrating to User Agent Client Hints](https://web.dev/migrate-to-ua-ch/) (Full guide)    
* 	[Strategy](https://web.dev/migrate-to-ua-ch/#strategy-on-demand-client-side-javascript-api) for navigator.userAgent users (JS API)    
* 	[Strategy](https://web.dev/migrate-to-ua-ch/#strategy-static-server-side-header) for Static server-side headers    
* 	[Delegating access](https://web.dev/migrate-to-ua-ch/#strategy:-delegating-hints-to-cross-origin-requests) of your high entropy hints to 3P resources    
* 	Handling critical [first request](https://web.dev/migrate-to-ua-ch/#strategy:-server-side-hints-required-on-first-request) client hints beyond the default set
	* The default set of hints includes the browser name with major version, the platform, and the mobile indicator.
    

Testing
-------

*   Chrome Browser - Please use chrome://flags/#reduce-user-agent    
*	Chrome Webdriver (Selenium testing, regression testing)
	*   \--enable-features=ReduceUserAgent
*   [User-Agent reduction code snippets](https://developer.chrome.com/docs/privacy-sandbox/user-agent/snippets/)
*   [Headers & JS API demo](https://web.dev/user-agent-client-hints/#demo)

**Comment by tapananand** [comment]
@faisalman Thanks for the above commit. I see that we are now falling back to UA-CH as you mentioned. But since we are still first getting the values from the UA string, won't we get wrong results now in some cases? For example, the OS version. Is the recommendation here to not use UA parser for those cases and instead directly use getHighEntropyValues API?

**Comment by tapananand** [comment]
@faisalman Can you please comment on the above?

**Comment by faisalman** [comment]
@tapananand for the time being, yes, but I don't rule out adding the client-hints API into this library in the near future..

**Comment by faisalman** [comment]
Moving user agent client hints-related issue here: #408
