### ISSUE TITLE
Is this package a lead generation tool for the "51Degrees UAParser" cloud service?

### ISSUE THREAD

**Issue by sintaxi** [faisalman/ua-parser-js#634]
No judgments, I know maintaining an open source package is a thankless job. However, I would appreciate some clarification on the role between this library, its backers, and its sponsors. Thank you.

**Question 1)** This package appears to have several backers and is also sponsored by "51Degrees". Are the authors of this package aware that 51Degrees is sending non-solicited email to users of this package telling them this library is "out of date" and instructing them to switch from `faisalman/ua-parser-js` to `@51degrees/ua-parser-js`? 

**Question 2)** It looks like with `@51Degrees/ua-parser-js` one needs to signup for a “resource key” and then user device data is sent to 51Degrees Cloud Services. Do the backers of this project know this library is being used for lead generation by its primary sponsor?

<img width="956" alt="Screenshot 2023-03-08 at 10 12 17 AM" src="https://user-images.githubusercontent.com/867/223807918-b70af7e9-1819-4bbc-82a9-20a403ca0afd.png">

**Comment by faisalman** [comment]
Hi @sintaxi, thanks for using UAParser.js, here's my take on the questions:

**Answer 1)** The benefits of being a sponsor have been outlined at https://opencollective.com/ua-parser-js: they will be featured in special placements on [1] documentation page & [2] demo page. Other than those mentioned placement which I have control over, certainly is not something that I'm aware of.

**Answer 2)** I don't know if by offering a space for sponsor can be seen as merely a tool, since every sponsored placement is most likely a "lead generation". From what I read, they are offering a cloud service with UAParser.js-compatible API which has its own advantages and drawbacks  depend on one's requirements and priorities (3rd-party solution vs in-house customization, detection accuracy, level of complexity, open-source license, price, etc). So I believe it's not something that can completely replace this package, but rather as a complement when you need something more extensive.

I hope it's clear, let me know if there's something that still needs to be clarified.

**Comment by sintaxi** [comment]
@faisalman thank you. That does clarify things for me. Much appreciated. 🙏

**Comment by jwrosewell** [comment]
I've just seen the post and wanted to support @faisalman's response as the founder of [51degrees](https://github.com/51degrees) and product lead on the 51Degrees [cloud backed modification](https://github.com/51Degrees/ua-parser-js).

My only addition is that we were unaware @faisalman was updating the project to support UACH at the time of the email contact referenced. Awesome that UAParser is being updated and that there are at least two ways forward for those in the UA Parser world.
