### ISSUE TITLE
Chrome Browser Full Version issue

### ISSUE THREAD

**Issue by Enfs-dev** [faisalman/ua-parser-js#635]
![image](https://user-images.githubusercontent.com/127836379/224948802-a0ff4b4b-ed30-469b-9455-164b6acb54fe.png)
![image](https://user-images.githubusercontent.com/127836379/225280410-c2b86bde-9ad7-40a8-9db8-ac6c8639b9ce.png)

If we observe above images, 
The package is giving only major version of the browser (111.0.0.0) and not minor versions, where as the real complete version of the browser is 111.0.5563.64.

 Please look into it.

**Comment by faisalman** [comment]
It is the intended behavior since Chrome starts hiding the full version in favor of user agent client hints. You can track the related issue here: #408

https://developer.chrome.com/blog/user-agent-reduction-android-model-and-version/

**Comment by newinfinity12** [comment]
> It is the intended behavior since Chrome starts hiding the full version in favor of user agent client hints. You can track the related issue here: #408
> 
> https://developer.chrome.com/blog/user-agent-reduction-android-model-and-version/

Hey I have this game issue however the correct full version is provided in the client hints however it is prioritizing the user-agent version instead of the client hint full version
![win11](https://github.com/faisalman/ua-parser-js/assets/52183370/85f503ff-3925-4a4f-85c9-559f79617d33)
![ch](https://github.com/faisalman/ua-parser-js/assets/52183370/6e9b5348-e501-4ecd-8543-2d9f1c4f3b1b)
