### ISSUE TITLE
Operation system from microsoft events not parsed

### ISSUE THREAD

**Issue by Volna13** [faisalman/ua-parser-js#646]
We have events from MS that contain Useragent string.

Here is example of useragents:
1. "Microsoft Office/16.0 (OMDroid 13; Microsoft Office Mobile 16.0.16227; Pro)"
2. "Microsoft Office PowerPoint/16.71.312 (Mac OS/13.2.1; Desktop; en-US; AppStore; Apple/MacBookPro16,1)"
3. "Microsoft Office Excel/16.0 (OMDroid 10; Microsoft Excel 16.0; Pro)"

uaParser return empty response.

Expected response (for example for 2)
```
{
  "ua": "Microsoft Office PowerPoint/16.71.312 (Mac OS/13.2.1; Desktop; en-US; AppStore; Apple/MacBookPro16,1)",
  "browser": {},
  "engine": {},
  "os": {
    "name": "Mac OS",
    "version": "13.2.1"
   },
  "device": {
    "vendor": "Apple",
    "model": "iPhone",
    "type": "mobile"
  },
  "cpu": {}
}
```

Current "ua-parser-version" - "ua-parser-js": "^1.0.35"

if "Mac OS/13.2.1" is problem we can convert it to "Mac OS 13.2.1"

**Comment by faisalman** [comment]
Hi, can you provide more context to this issue? please use this format for clarity:

--
**Library version**
Which version of the library that you use, eg: v0.7.35 or v2.0.0-alpha.3

For the issue related with detection result, you can use the demo section in https://uaparser.js.org to confirm

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by faisalman** [comment]
I'm closing this for now, please don't hesitate to re-open this issue again using the given format, thanks!
