### ISSUE TITLE
Getting Wrong Device Specifiction

### ISSUE THREAD

**Issue by ShashikantMauryaOnbe** [faisalman/ua-parser-js#648]
Hi All,

I am using ua-parser to get device details, its working for most of the Samsung devices but unable to get device details when I am parsing Samsung S21.

When I am **trying to google what is my User Agent** it gives like and seems to correct : **Mozilla/5.0 (Linux; Android 13; SM-G991U Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36 GoogleApp/[14.12.16.26](http://14.12.16.26/).arm64**

but **UA parser user agent returned** like : **Mozila/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36**

![image](https://user-images.githubusercontent.com/119935277/232751376-e294ad9a-87d4-4aa4-b995-285f46a001bf.png)

please help me out.

**Comment by PrajwalVBharadwaj** [comment]
Facing the same issue. Read a thread on chrome developer docs about [user agent reduction](https://developer.chrome.com/en/docs/privacy-sandbox/user-agent/), has it got anything to do with this? If yes then is anyone who has found a solution?

**Comment by PrajwalVBharadwaj** [comment]
Parsing the userAgent string from the navigator object will not work from Chrome V113 due to user agent reduction. You can read the rollout plan in [here](https://www.chromium.org/updates/ua-reduction/#TOC-Proposed-Rollout-Plan).
The proposed solution is [User Agent Client hints](https://web.dev/migrate-to-ua-ch/).
It will be great if this can be taken as a feature request for the package and a promise based API is exposed.

**Comment by PrajwalVBharadwaj** [comment]
@ShashikantMauryaOnbe this is due to User agent reduction. The package already supports user agent client hints. Please refer [this](https://web.dev/migrate-to-ua-ch/). Starting chrome version 113 User agent reduction will be rolled out to 100% android devices. You can find the rollout plan [here](https://www.chromium.org/updates/ua-reduction/#TOC-Proposed-Rollout-Plan).

[User Agent client hints.](https://web.dev/migrate-to-ua-ch/)

**Comment by faisalman** [comment]
See if the device details can be obtained using client hints: https://faisalman.github.io/ua-parser-js/#demo

`npm i ua-parser-js@2.0.0-alpha.2`

`await parser.getDevice().withClientHints()`

https://faisalman.github.io/ua-parser-js-docs/v2/api/ua-parser-js/idata/with-client-hints.html
