### ISSUE TITLE
红米note8 手机的ua 解析不出移动端

### ISSUE THREAD

**Issue by feikeq** [faisalman/ua-parser-js#723]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/109.0.5414.118 Safari/534.24 XiaoMi/MiuiBrowser/17.9.161211 swan-mibrowser

**Comment by faisalman** [comment]
Hi, can you provide more context to this issue? please use this format for clarity:

--
**Library version**
Which version of the library that you use, eg: v0.7.35 or v2.0.0-alpha.3

For the issue related with detection result, you can use the demo section in https://uaparser.js.org to confirm

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by faisalman** [comment]
I'm closing this for now, please don't hesitate to re-open this issue again using the given format, thanks!
