### ISSUE TITLE
Invocation error

### ISSUE THREAD

**Issue by MyRichard12** [faisalman/ua-parser-js#757]
**Library version**
2.0.0-rc.1

In TypeScript

Invocation returns error

```
new UAParser(req.headers['user-agent']);

// This expression is not constructable.
 // Type 'typeof UAParser' has no construct signatures.ts

**Comment by faisalman** [comment]
Hi, thanks for the report, can you provide a minimum reproducible example that we can investigate?

**Comment by faisalman** [comment]
I'm closing this for now, please reopen if you still facing the issue

**Comment by buzzy** [comment]
I get the same issue when upgrading from v1 to v2. 

const parser = new UAParser() simply does not work because the UAParser is regarded at "type UAParser" by eslint.

doing cost test = UAParser shows that test has the value "type UAParser"

Right-clicking and picking "type defintion" in vscode goes to the ua-parser.d.ts v2.0.2 file, so it does not look like something is configured wrong.

**Comment by buzzy** [comment]
Ok, if anyone else stumbles upon this, here is how I solved it:

Change the import to:
import { UAParser } from 'ua-parser-js';

Then use UAParser function directly instead of as a class:
const parserResults = UAParser(userAgent);
